/* WordCourt drills — original practice sets, auto-graded. Content only; UI in drills.js.
   Item types: numeric (typed answer), mc (A–E), completion (ISEE sentence completion), analogy (bridge first),
   reading (passage-linked), checklist (platform review, self-marked), card (read-only). */
window.WORDCOURT_DRILLS = {
  skills: {
    'scale-area': 'Scaling: area × k²', 'scale-volume': 'Scaling: volume × k³', 'lcm-product': 'LCM vs. least product',
    'stats-median-grouped': 'Median from table / histogram', 'stats-weighted-mean': 'Weighted mean', 'stats-mean-median-effect': 'Changes to mean vs. median',
    'stats-mean': 'Mean', 'answer-asked': 'Answer the question asked', 'chart-read': 'Reading a chart', 'percent-chain': 'Percent change chains',
    'perimeter-area': 'Perimeter / area setup', 'rate-time': 'Rate × time, unit slips', 'venn': 'Overlapping sets', 'reverse-percent': 'Reverse percentage',
    'speed-range': 'Average-speed bounds', 'segment-algebra': 'Segment addition algebra', 'function-notation': 'Function notation f(x+a)',
    'cube-packing': 'Cubes in a cube', 'prob-mult': 'Probability: multiply', 'prob-noreplace': 'Probability without replacement',
    'revenue-balance': 'Revenue balance', 'estimation': 'Estimation direction', 'sign-reversal': 'Reversed difference / sign',
    'spatial-view': 'Views of solids', 'triangle-area': 'Triangle area', 'sum-series': 'Sums of consecutive integers', 'factors': 'Factors (1 counts)',
    'qc-algebra': 'QC: simplify both columns', 'qc-boundary': 'QC: boundary > vs ≥', 'qc-label': 'QC: compare the right group', 'qc-not-to-scale': 'QC: not drawn to scale',
    'polygon-angles': 'Polygon angle formula', 'counting-pairs': 'Counting pairs / handshakes', 'negatives-magnitude': 'Negatives: magnitude vs. value',
    'qc-assumed-similarity': 'QC: unstated similarity', 'qc-one-case': 'QC: one case is not proof', 'grid-area': 'Area on a grid', 'radicals': 'Radicals',
    'fraction-zero': 'Fraction = 0 (numerator only)', 'unit-conversion': 'Unit conversion', 'inequality-translate': 'Number line → inequality',
    'imaginary': 'Imaginary numbers', 'distance-formula': 'Distance formula', 'gcf': 'GCF of monomials', 'sequence-explicit': 'Explicit nth term',
    'coordinate-geometry': 'Coordinate geometry', 'rational-equation': 'Rational equations', 'trig-ratio': 'Trig ratios (SOH-CAH-TOA)',
    'rd-main-idea': 'Reading: main idea (not too narrow)', 'rd-detail': 'Reading: detail (re-find the line)', 'rd-relationship': 'Reading: reversed relationship',
    'rd-tone': 'Reading: tone / attitude', 'rd-inference': 'Reading: inference (not anti-thesis)', 'rd-century': 'Reading: century / date arithmetic',
    'rd-vocab': 'Reading: vocabulary in context', 'rd-purpose': 'Reading: paragraph purpose', 'rd-sequence': 'Reading: sequence of events',
    'rd-pacing': 'Reading: pacing (reached in time)', 'vocab-completion': 'Sentence completions', 'analogy-bridge': 'Analogy bridges', 'timed': 'Timed section pacing',
  },

  sets: [
    /* ==================== DAY 1 ==================== */
    {
      id: 'sep1_d1_warmup', day: 'Day 1 · Tue Sept 1', availableFrom: '2026-09-01', order: 10,
      title: 'Warm-Up', subtitle: '3 questions · typed answers', scoring: 'none', timeLimitS: null,
      items: [
        { id: 'd1w1', type: 'numeric', skills: ['scale-volume'], prompt: 'The radius and the height of a cylinder are both doubled. The volume of the cylinder is multiplied by what number?', answer: '8',
          explain: '$V = \\pi r^2 h$. Doubling $r$ multiplies $V$ by $2^2 = 4$; doubling $h$ multiplies by 2; together $4 \\times 2 = 8$. All three dimensions double, so volume scales by $2^3$.' },
        { id: 'd1w2', type: 'numeric', skills: ['scale-area'], prompt: 'The radius of a sphere is multiplied by 4. The surface area of the sphere is multiplied by what number?', answer: '16',
          explain: 'Surface area is a two-dimensional measure: it scales by the square of the length factor, $4^2 = 16$.' },
        { id: 'd1w3', type: 'numeric', skills: ['lcm-product'], prompt: '$x$ is a positive multiple of 6 and $y$ is a positive multiple of 10. What is the least possible value of the product $xy$?', answer: '60',
          explain: 'The least positive multiple of 6 is 6 and of 10 is 10; the least product is $6 \\times 10 = 60$. The least common multiple (30) answers a different question.' },
      ],
    },
    {
      id: 'sep1_d1_stats', day: 'Day 1 · Tue Sept 1', availableFrom: '2026-09-01', order: 20,
      title: 'Statistics from Grouped Data', subtitle: 'ISEE rules · 2 worked examples + 4 questions', scoring: 'isee', timeLimitS: null,
      intro: [
        { type: 'directions', html: '<b>Directions:</b> Read the two worked examples, then answer the four questions that follow. Each question has four suggested answers. Select the best answer.' },
        { type: 'reference', title: 'Reference — Median and Mean from a Table or Histogram', html: 'A histogram or frequency table is a compressed list. To find the <b>median</b>, decompress it: count how many values there are in total ($n$), locate the middle position — the $\\tfrac{n+1}{2}$th value when $n$ is odd, the average of the $\\tfrac{n}{2}$th and $\\left(\\tfrac{n}{2}+1\\right)$th values when $n$ is even — and count up through the bars or rows until that position is reached. The median is a <i>data value</i> (a bar\'s label), never the middle of the axis and never the average of the labels.<br>For the <b>mean</b>, multiply each value by its frequency, add, and divide by $n$. A score that "counts twice" has a weight of 2: it is added twice to the numerator and adds 2 to the denominator.' },
        { type: 'example', title: 'Worked Example 1 — median and mean from a frequency table', html: 'The table shows the number of pets in each of 15 households.<table class="dtable"><tr><th>Pets</th><td>0</td><td>1</td><td>2</td><td>3</td><td>4</td></tr><tr><th>Households</th><td>4</td><td>5</td><td>3</td><td>2</td><td>1</td></tr></table><i>Median.</i> $n = 15$, so the median is the 8th value. Counting up: the "0" row covers positions 1–4; the "1" row covers positions 5–9. Position 8 falls in the "1" row. <b>Median = 1.</b><br><i>Mean.</i> $\\dfrac{0(4)+1(5)+2(3)+3(2)+4(1)}{15} = \\dfrac{21}{15} = 1.4$. The mean (1.4) and the median (1) are different questions with different answers — check which one is asked.' },
        { type: 'example', title: 'Worked Example 2 — a weighted mean with an unknown', html: 'A student\'s four test scores are 82, 90, 78, and 86. The final exam counts twice as much as one test. What final-exam score gives the student an overall mean of 85?<br>Total weight $= 4 + 2 = 6$. The required total is $85 \\times 6 = 510$. The tests contribute $82+90+78+86 = 336$. So $336 + 2x = 510$, giving $2x = 174$ and $x = 87$.<br>Check: $\\dfrac{336 + 2(87)}{6} = \\dfrac{510}{6} = 85$ ✓ — the final counts twice in the numerator <i>and</i> twice in the denominator.' },
      ],
      items: [
        { id: 'd1s1', type: 'mc', skills: ['stats-median-grouped'], figure: 'hist_books',
          prompt: 'The histogram shows the number of books read over the summer by the 24 students in a class. What is the median number of books read?',
          choices: [['A', '1'], ['B', '2'], ['C', '2.5'], ['D', '3']], answer: 'B',
          explain: '$n = 24$, so the median is the average of the 12th and 13th values. Cumulative counts: 0 books → positions 1–3; 1 book → 4–8; 2 books → 9–15. Both the 12th and 13th values are 2. Choice (C) is the middle of the axis; neither (C) nor (D) is a data value in the middle position.' },
        { id: 'd1s2', type: 'mc', skills: ['stats-median-grouped'],
          prompt: 'The table shows the years of service of the 11 employees of a company. What is the median number of years of service?<table class="dtable"><tr><th>Years of service</th><td>1</td><td>3</td><td>5</td><td>8</td><td>12</td></tr><tr><th>Number of employees</th><td>2</td><td>3</td><td>2</td><td>3</td><td>1</td></tr></table>',
          choices: [['A', '3'], ['B', '5'], ['C', '5.8'], ['D', '6.5']], answer: 'B',
          explain: '$n = 11$, median is the 6th value. Cumulative: 1 yr → 1–2; 3 yr → 3–5; 5 yr → 6–7. The 6th value is 5. Choice (C) is the average of the five labels, which is not a statistic of the data.' },
        { id: 'd1s3', type: 'mc', skills: ['stats-weighted-mean'],
          prompt: 'A student\'s four quiz scores are 75, 83, 91, and 79. The project counts twice as much as one quiz. What project score is needed for an overall mean of 84?',
          choices: [['A', '84'], ['B', '86'], ['C', '88'], ['D', '92']], answer: 'C',
          explain: 'Total weight $4 + 2 = 6$; required total $84 \\times 6 = 504$; quizzes contribute $75+83+91+79 = 328$; $2x = 176$, $x = 88$.' },
        { id: 'd1s4', type: 'mc', skills: ['stats-mean-median-effect'],
          prompt: 'A set of 20 test scores has a mean of 78 and a median of 80. Two students whose scores were below the median retake the test, and each raises his or her score by 10 points, but both scores remain below the median. Which of the following describes the new mean and median?',
          choices: [['A', 'The mean is 79 and the median is 80.'], ['B', 'The mean is 79 and the median is 81.'], ['C', 'The mean is 78 and the median is 80.'], ['D', 'The mean is 80 and the median is 80.']], answer: 'A',
          explain: 'The total rises by $2 \\times 10 = 20$ points over 20 scores, so the mean rises by 1, to 79. Both changed scores stay below the median, so the ordered list\'s middle values are unchanged: the median stays 80.' },
      ],
    },
    {
      id: 'sep1_d1_multistep', day: 'Day 1 · Tue Sept 1', availableFrom: '2026-09-01', order: 30,
      title: 'Multi-Step Problems', subtitle: 'SSAT rules · 6 questions · 12 minutes', scoring: 'ssat', timeLimitS: 720,
      intro: [
        { type: 'directions', html: '<b>Directions:</b> Following each problem there are five suggested answers. Work each problem on scratch paper, then decide which answer is best. <b>Scoring:</b> +1 correct, −¼ incorrect, 0 blank.' },
        { type: 'reference', title: 'Strategy Reference — Answer the Question Asked', html: 'After computing, re-read the <b>last sentence</b> of the question and check that the number found is the thing it asks for. The most common final steps that get skipped: subtracting from a total, combining two categories, converting the unit, finding the <i>other</i> variable, and multiplying the quantity just found. The intermediate number is almost always one of the answer choices.' },
      ],
      items: [
        { id: 'd1m1', type: 'mc', skills: ['chart-read', 'answer-asked'], figure: 'pie_lunch',
          prompt: '<i>Questions 1 and 2 refer to the chart.</i><br>What fraction of the students chose pizza or salad?',
          choices: [['A', '$\\tfrac{7}{20}$'], ['B', '$\\tfrac{47}{100}$'], ['C', '$\\tfrac{12}{25}$'], ['D', '$\\tfrac{53}{100}$'], ['E', '$\\tfrac{3}{5}$']], answer: 'B',
          explain: 'Pizza or salad $= 35\\% + 12\\% = 47\\% = \\tfrac{47}{100}$. Choice (A) is pizza alone.' },
        { id: 'd1m2', type: 'mc', skills: ['chart-read', 'answer-asked'],
          prompt: 'How many more students chose tacos than chose soup?',
          choices: [['A', '16'], ['B', '17'], ['C', '34'], ['D', '50'], ['E', '66']], answer: 'C',
          explain: 'Tacos minus soup $= 25\\% - 8\\% = 17\\%$ of 200 students $= 34$ students. Choice (B) is the difference in percentage points, not in students; choice (D) is the number who chose tacos.' },
        { id: 'd1m3', type: 'mc', skills: ['answer-asked'],
          prompt: 'If $\\tfrac{1}{4}a + \\tfrac{1}{4}b = 6$, what is the value of $5a + 5b$?',
          choices: [['A', '24'], ['B', '30'], ['C', '96'], ['D', '120'], ['E', '150']], answer: 'D',
          explain: '$\\tfrac{1}{4}(a+b) = 6 \\Rightarrow a + b = 24 \\Rightarrow 5(a+b) = 120$. Choice (A) is $a+b$, the intermediate step.' },
        { id: 'd1m4', type: 'mc', skills: ['percent-chain', 'answer-asked'],
          prompt: 'A theater sold 480 tickets on Friday. On Saturday it sold 15% more tickets than on Friday, and on Sunday it sold 60 fewer tickets than on Saturday. How many tickets were sold on Sunday?',
          choices: [['A', '420'], ['B', '492'], ['C', '540'], ['D', '552'], ['E', '612']], answer: 'B',
          explain: 'Saturday $= 480 \\times 1.15 = 552$; Sunday $= 552 - 60 = 492$. Choice (D) is Saturday\'s count.' },
        { id: 'd1m5', type: 'mc', skills: ['perimeter-area', 'answer-asked'],
          prompt: 'The perimeter of a rectangle is 54 centimeters, and its length is 5 centimeters more than its width. What is the area of the rectangle, in square centimeters?',
          choices: [['A', '11'], ['B', '16'], ['C', '27'], ['D', '176'], ['E', '352']], answer: 'D',
          explain: '$2(w + w + 5) = 54 \\Rightarrow 2w + 5 = 27 \\Rightarrow w = 11$, length 16; area $= 11 \\times 16 = 176$. Choices (A) and (B) are the dimensions.' },
        { id: 'd1m6', type: 'mc', skills: ['rate-time'],
          prompt: 'A runner completes 3 laps of a track in 4 minutes 30 seconds. At the same pace, how long will it take the runner to complete 5 laps?',
          choices: [['A', '6 minutes 00 seconds'], ['B', '7 minutes 00 seconds'], ['C', '7 minutes 30 seconds'], ['D', '7 minutes 50 seconds'], ['E', '8 minutes 30 seconds']], answer: 'C',
          explain: '4 min 30 s $= 270$ s; per lap $270 \\div 3 = 90$ s; five laps $= 450$ s $= 7$ min 30 s. Choice (D) comes from reading 7.5 minutes as 7:50.' },
      ],
    },
    {
      id: 'sep1_d1_review', day: 'Day 1 · Tue Sept 1', availableFrom: '2026-09-01', order: 40,
      title: 'Review Set — Test Innovators', subtitle: 'Rework each question cold on the platform, then mark it', scoring: 'none', timeLimitS: null,
      intro: [{ type: 'directions', html: '<b>Directions:</b> Open each question on Test Innovators and rework it <b>cold</b> — solution closed, from the question alone. Mark ✓ or ✗ here. For each ✗, read the platform\'s solution and write the error-log line when prompted.' }],
      items: [
        { id: 'd1r1', type: 'checklist', skills: ['answer-asked', 'chart-read'], prompt: 'SSAT Upper #3 · Section 1 · Question 20' },
        { id: 'd1r2', type: 'checklist', skills: ['answer-asked', 'chart-read'], prompt: 'SSAT Upper #3 · Section 1 · Question 21' },
        { id: 'd1r3', type: 'checklist', skills: ['estimation'], prompt: 'SSAT Upper #3 · Section 4 · Question 4' },
        { id: 'd1r4', type: 'checklist', skills: ['answer-asked'], prompt: 'ISEE Upper #2 · Quantitative Reasoning · Question 12' },
        { id: 'd1r5', type: 'checklist', skills: ['stats-median-grouped'], prompt: 'ISEE Upper #2 · Mathematics Achievement · Question 33' },
        { id: 'd1r6', type: 'checklist', skills: ['stats-weighted-mean'], prompt: 'ISEE Upper #2 · Mathematics Achievement · Question 34' },
        { id: 'd1r7', type: 'checklist', skills: ['stats-median-grouped'], prompt: 'ISEE Upper #2 · Mathematics Achievement · Question 35' },
      ],
    },

    /* ==================== DAY 2 ==================== */
    {
      id: 'sep1_d2_warmup', day: 'Day 2 · Wed Sept 2', availableFrom: '2026-09-02', order: 50,
      title: 'Warm-Up', subtitle: '3 questions · typed answers', scoring: 'none', timeLimitS: null,
      items: [
        { id: 'd2w1', type: 'numeric', skills: ['scale-volume'], prompt: 'The edge of a cube is multiplied by 5. The volume of the cube is multiplied by what number?', answer: '125',
          explain: 'Volume scales by the cube of the length factor: $5^3 = 125$.' },
        { id: 'd2w2', type: 'numeric', skills: ['answer-asked'], prompt: 'If $2x + 2y = 18$, what is the average (arithmetic mean) of $x$ and $y$?', answer: '4.5', accept: ['9/2', '4 1/2'],
          explain: '$x + y = 9$; the mean is $\\tfrac{x+y}{2} = 4.5$. The sum is the intermediate step, not the answer.' },
        { id: 'd2w3', type: 'numeric', skills: ['prob-mult'], prompt: 'A spinner has 8 equal sections numbered 1 through 8. It is spun twice. What is the probability that both spins land on a prime number? (Enter a fraction such as 3/8.)', answer: '1/4', accept: ['0.25', '.25', '2/8', '25%'],
          explain: 'Primes from 1 to 8: 2, 3, 5, 7, so $P(\\text{prime}) = \\tfrac{4}{8} = \\tfrac{1}{2}$ on each spin; both: $\\tfrac{1}{2} \\times \\tfrac{1}{2} = \\tfrac{1}{4}$.' },
      ],
    },
    {
      id: 'sep1_d2_quant', day: 'Day 2 · Wed Sept 2', availableFrom: '2026-09-02', order: 60,
      title: 'Quantitative Mini-Section', subtitle: 'SSAT rules · 10 questions · 10 minutes · timed', scoring: 'ssat', timeLimitS: 600,
      intro: [{ type: 'directions', html: '<b>Directions:</b> The timer starts when you press Begin. Following each problem there are five suggested answers. Work each problem on scratch paper, then decide which answer is best. <b>Scoring:</b> +1 correct, −¼ incorrect, 0 blank. Leave a question blank unless you have worked it or eliminated at least two choices. When time runs out the section submits itself.' }],
      items: [
        { id: 'd2q1', type: 'mc', skills: ['venn'], prompt: 'In a class of 30 students, 18 play soccer and 15 play basketball. If 5 students play neither sport, how many students play both?',
          choices: [['A', '3'], ['B', '5'], ['C', '8'], ['D', '10'], ['E', '13']], answer: 'C',
          explain: 'Students in at least one sport $= 30 - 5 = 25$. Then $18 + 15 - \\text{both} = 25$, so both $= 8$.' },
        { id: 'd2q2', type: 'mc', skills: ['reverse-percent'], prompt: 'After a 20% discount, a jacket costs \\$68. What was the original price of the jacket?',
          choices: [['A', '\\$54.40'], ['B', '\\$81.60'], ['C', '\\$85.00'], ['D', '\\$88.00'], ['E', '\\$136.00']], answer: 'C',
          explain: 'The sale price is 80% of the original: $0.80x = 68 \\Rightarrow x = 85$. Choice (B) adds 20% to the sale price, which undoes nothing.' },
        { id: 'd2q3', type: 'mc', skills: ['speed-range'], prompt: 'A car travels 210 miles in more than 3 hours but less than 3½ hours. The car\'s average speed, in miles per hour, must be between',
          choices: [['A', '50 and 60'], ['B', '60 and 70'], ['C', '65 and 75'], ['D', '70 and 80'], ['E', '75 and 85']], answer: 'B',
          explain: '$210 \\div 3.5 = 60$ and $210 \\div 3 = 70$; the speed lies between 60 and 70 mph. The longer the time, the lower the speed.' },
        { id: 'd2q4', type: 'mc', skills: ['segment-algebra', 'answer-asked'], prompt: 'Points $A$, $B$, and $C$ lie on a line in that order. If $AC = 30$, $BC = x + 4$, and $AB = 2x - 1$, what is the length of $AB$?',
          choices: [['A', '9'], ['B', '13'], ['C', '17'], ['D', '21'], ['E', '27']], answer: 'C',
          explain: '$AB + BC = AC$: $(2x - 1) + (x + 4) = 30 \\Rightarrow 3x = 27 \\Rightarrow x = 9$. The question asks for $AB = 2(9) - 1 = 17$. Choice (A) is $x$; choice (B) is $BC$.' },
        { id: 'd2q5', type: 'mc', skills: ['function-notation'], prompt: 'If $g(x - 3) = 4x + 1$, what is the value of $g(2)$?',
          choices: [['A', '9'], ['B', '13'], ['C', '17'], ['D', '21'], ['E', '25']], answer: 'D',
          explain: 'Solve the argument first: $x - 3 = 2 \\Rightarrow x = 5$. Then $g(2) = 4(5) + 1 = 21$. Choice (A) substitutes 2 for $x$ directly.' },
        { id: 'd2q6', type: 'mc', skills: ['cube-packing', 'scale-volume'], prompt: 'How many cubes with edges of length 2 centimeters can be packed, with no space left over, inside a cube with edges of length 8 centimeters?',
          choices: [['A', '4'], ['B', '16'], ['C', '32'], ['D', '64'], ['E', '512']], answer: 'D',
          explain: '$8 \\div 2 = 4$ small cubes along each edge; $4^3 = 64$. Choice (B) is $4^2$; choice (A) is the edge ratio alone.' },
        { id: 'd2q7', type: 'mc', skills: ['prob-noreplace', 'prob-mult'], prompt: 'A bag contains 3 red marbles and 5 blue marbles. Two marbles are drawn at random, one after the other, without replacement. What is the probability that both marbles are red?',
          choices: [['A', '$\\tfrac{3}{64}$'], ['B', '$\\tfrac{3}{28}$'], ['C', '$\\tfrac{9}{64}$'], ['D', '$\\tfrac{3}{8}$'], ['E', '$\\tfrac{3}{4}$']], answer: 'B',
          explain: 'Without replacement: $\\tfrac{3}{8} \\times \\tfrac{2}{7} = \\tfrac{6}{56} = \\tfrac{3}{28}$. Choice (C) assumes replacement.' },
        { id: 'd2q8', type: 'mc', skills: ['revenue-balance', 'answer-asked'], prompt: 'A store sells 500 notebooks at \\$4 each. If the price is raised to \\$5 each, how many fewer notebooks must the store sell to take in the same amount of money?',
          choices: [['A', '20'], ['B', '80'], ['C', '100'], ['D', '400'], ['E', '500']], answer: 'C',
          explain: 'Revenue $= 500 \\times 4 = 2000$ dollars. At \\$5 each, $2000 \\div 5 = 400$ notebooks; the question asks how many <i>fewer</i>: $500 - 400 = 100$. Choice (D) is the new count.' },
        { id: 'd2q9', type: 'mc', skills: ['estimation'], prompt: 'The value of $4.9 \\times 19.8 + 3.02 \\times 9.9$ is closest to',
          choices: [['A', '100'], ['B', '115'], ['C', '127'], ['D', '135'], ['E', '148']], answer: 'C',
          explain: '$4.9 \\times 19.8$ is just under $5 \\times 20 = 100$ (it is 97.02), and $3.02 \\times 9.9$ is just under 30 (it is 29.9). The total is about 127. Rounding both products up gives 130; tracking the rounding direction (both rounded up) confirms the answer is below 130.' },
        { id: 'd2q10', type: 'mc', skills: ['perimeter-area', 'answer-asked'], prompt: 'The area of a square is 144 square centimeters. A rectangle has a length twice the side of the square and a width half the side of the square. What is the perimeter of the rectangle, in centimeters?',
          choices: [['A', '30'], ['B', '48'], ['C', '60'], ['D', '144'], ['E', '288']], answer: 'C',
          explain: 'Side $= \\sqrt{144} = 12$. Length 24, width 6; perimeter $= 2(24 + 6) = 60$. Choice (D) is the square\'s area, choice (B) the square\'s perimeter.' },
      ],
    },
    {
      id: 'sep1_d2_review', day: 'Day 2 · Wed Sept 2', availableFrom: '2026-09-02', order: 70,
      title: 'Quantitative Review Set — Test Innovators', subtitle: 'Every listed question, cold · ~45 minutes', scoring: 'none', timeLimitS: null,
      intro: [{ type: 'directions', html: '<b>Directions:</b> Rework every question below <b>cold</b> on the platform — solution closed, from the question alone. Mark ✓ or ✗ here as you go. For each ✗: read the platform\'s solution and write the error-log line when prompted. Questions marked ✗ become Thursday\'s second-pass list automatically. The ISEE Quantitative Reasoning block is quantitative comparisons — say the QC directions and the four choices aloud before starting it.' }],
      items: [
        { id: 'd2r_s1_6', type: 'checklist', skills: ['speed-range'], prompt: 'SSAT #3 · Section 1 · Q6' },
        { id: 'd2r_s1_10', type: 'checklist', skills: ['prob-mult'], prompt: 'SSAT #3 · Section 1 · Q10' },
        { id: 'd2r_s1_17', type: 'checklist', skills: ['cube-packing'], prompt: 'SSAT #3 · Section 1 · Q17' },
        { id: 'd2r_s1_19', type: 'checklist', skills: ['function-notation'], prompt: 'SSAT #3 · Section 1 · Q19' },
        { id: 'd2r_s1_20', type: 'checklist', skills: ['answer-asked', 'chart-read'], prompt: 'SSAT #3 · Section 1 · Q20' },
        { id: 'd2r_s1_21', type: 'checklist', skills: ['answer-asked', 'chart-read'], prompt: 'SSAT #3 · Section 1 · Q21' },
        { id: 'd2r_s1_22', type: 'checklist', skills: ['venn'], prompt: 'SSAT #3 · Section 1 · Q22' },
        { id: 'd2r_s4_4', type: 'checklist', skills: ['estimation'], prompt: 'SSAT #3 · Section 4 · Q4' },
        { id: 'd2r_s4_6', type: 'checklist', skills: ['revenue-balance'], prompt: 'SSAT #3 · Section 4 · Q6' },
        { id: 'd2r_s4_7', type: 'checklist', skills: ['venn'], prompt: 'SSAT #3 · Section 4 · Q7' },
        { id: 'd2r_s4_14', type: 'checklist', skills: ['rate-time'], prompt: 'SSAT #3 · Section 4 · Q14' },
        { id: 'd2r_s4_24', type: 'checklist', skills: ['segment-algebra'], prompt: 'SSAT #3 · Section 4 · Q24' },
        { id: 'd2r_s4_25', type: 'checklist', skills: ['reverse-percent'], prompt: 'SSAT #3 · Section 4 · Q25' },
        { id: 'd2r_qr_2', type: 'checklist', skills: ['spatial-view'], prompt: 'ISEE #2 · Quantitative Reasoning · Q2' },
        { id: 'd2r_qr_3', type: 'checklist', skills: ['stats-mean'], prompt: 'ISEE #2 · Quantitative Reasoning · Q3' },
        { id: 'd2r_qr_6', type: 'checklist', skills: ['triangle-area'], prompt: 'ISEE #2 · Quantitative Reasoning · Q6' },
        { id: 'd2r_qr_7', type: 'checklist', skills: ['stats-mean-median-effect'], prompt: 'ISEE #2 · Quantitative Reasoning · Q7' },
        { id: 'd2r_qr_8', type: 'checklist', skills: ['sum-series'], prompt: 'ISEE #2 · Quantitative Reasoning · Q8' },
        { id: 'd2r_qr_11', type: 'checklist', skills: ['perimeter-area'], prompt: 'ISEE #2 · Quantitative Reasoning · Q11' },
        { id: 'd2r_qr_12', type: 'checklist', skills: ['answer-asked'], prompt: 'ISEE #2 · Quantitative Reasoning · Q12' },
        { id: 'd2r_qr_13', type: 'checklist', skills: ['chart-read'], prompt: 'ISEE #2 · Quantitative Reasoning · Q13' },
        { id: 'd2r_qr_14', type: 'checklist', skills: ['lcm-product'], prompt: 'ISEE #2 · Quantitative Reasoning · Q14' },
        { id: 'd2r_qr_16', type: 'checklist', skills: ['percent-chain'], prompt: 'ISEE #2 · Quantitative Reasoning · Q16' },
        { id: 'd2r_qr_17', type: 'checklist', skills: ['scale-area'], prompt: 'ISEE #2 · Quantitative Reasoning · Q17' },
        { id: 'd2r_qr_18', type: 'checklist', skills: ['factors'], prompt: 'ISEE #2 · Quantitative Reasoning · Q18' },
        { id: 'd2r_qr_19', type: 'checklist', skills: ['qc-algebra'], prompt: 'ISEE #2 · QR (quantitative comparison) · Q19' },
        { id: 'd2r_qr_22', type: 'checklist', skills: ['qc-boundary'], prompt: 'ISEE #2 · QR (quantitative comparison) · Q22' },
        { id: 'd2r_qr_23', type: 'checklist', skills: ['qc-label'], prompt: 'ISEE #2 · QR (quantitative comparison) · Q23' },
        { id: 'd2r_qr_25', type: 'checklist', skills: ['qc-not-to-scale'], prompt: 'ISEE #2 · QR (quantitative comparison) · Q25' },
        { id: 'd2r_qr_28', type: 'checklist', skills: ['polygon-angles'], prompt: 'ISEE #2 · QR (quantitative comparison) · Q28' },
        { id: 'd2r_qr_31', type: 'checklist', skills: ['counting-pairs'], prompt: 'ISEE #2 · QR (quantitative comparison) · Q31' },
        { id: 'd2r_qr_34', type: 'checklist', skills: ['negatives-magnitude'], prompt: 'ISEE #2 · QR (quantitative comparison) · Q34' },
        { id: 'd2r_qr_36', type: 'checklist', skills: ['qc-assumed-similarity'], prompt: 'ISEE #2 · QR (quantitative comparison) · Q36' },
        { id: 'd2r_qr_37', type: 'checklist', skills: ['qc-one-case'], prompt: 'ISEE #2 · QR (quantitative comparison) · Q37' },
        { id: 'd2r_ma_15', type: 'checklist', skills: ['grid-area'], prompt: 'ISEE #2 · Mathematics Achievement · Q15' },
        { id: 'd2r_ma_16', type: 'checklist', skills: ['prob-mult'], prompt: 'ISEE #2 · Mathematics Achievement · Q16' },
        { id: 'd2r_ma_18', type: 'checklist', skills: ['radicals'], prompt: 'ISEE #2 · Mathematics Achievement · Q18' },
        { id: 'd2r_ma_19', type: 'checklist', skills: ['answer-asked'], prompt: 'ISEE #2 · Mathematics Achievement · Q19' },
        { id: 'd2r_ma_21', type: 'checklist', skills: ['reverse-percent'], prompt: 'ISEE #2 · Mathematics Achievement · Q21' },
        { id: 'd2r_ma_22', type: 'checklist', skills: ['fraction-zero'], prompt: 'ISEE #2 · Mathematics Achievement · Q22' },
        { id: 'd2r_ma_23', type: 'checklist', skills: ['unit-conversion'], prompt: 'ISEE #2 · Mathematics Achievement · Q23' },
        { id: 'd2r_ma_33', type: 'checklist', skills: ['stats-median-grouped'], prompt: 'ISEE #2 · Mathematics Achievement · Q33' },
        { id: 'd2r_ma_34', type: 'checklist', skills: ['stats-weighted-mean'], prompt: 'ISEE #2 · Mathematics Achievement · Q34' },
        { id: 'd2r_ma_35', type: 'checklist', skills: ['stats-median-grouped'], prompt: 'ISEE #2 · Mathematics Achievement · Q35' },
        { id: 'd2r_ma_36', type: 'checklist', skills: ['inequality-translate'], prompt: 'ISEE #2 · Mathematics Achievement · Q36' },
        { id: 'd2r_ma_38', type: 'checklist', skills: ['imaginary'], prompt: 'ISEE #2 · Mathematics Achievement · Q38' },
        { id: 'd2r_ma_39', type: 'checklist', skills: ['distance-formula'], prompt: 'ISEE #2 · Mathematics Achievement · Q39' },
        { id: 'd2r_ma_42', type: 'checklist', skills: ['gcf'], prompt: 'ISEE #2 · Mathematics Achievement · Q42' },
        { id: 'd2r_ma_43', type: 'checklist', skills: ['sequence-explicit'], prompt: 'ISEE #2 · Mathematics Achievement · Q43' },
        { id: 'd2r_ma_44', type: 'checklist', skills: ['coordinate-geometry'], prompt: 'ISEE #2 · Mathematics Achievement · Q44' },
        { id: 'd2r_ma_45', type: 'checklist', skills: ['function-notation'], prompt: 'ISEE #2 · Mathematics Achievement · Q45' },
        { id: 'd2r_ma_46', type: 'checklist', skills: ['rational-equation'], prompt: 'ISEE #2 · Mathematics Achievement · Q46' },
        { id: 'd2r_ma_47', type: 'checklist', skills: ['trig-ratio'], prompt: 'ISEE #2 · Mathematics Achievement · Q47' },
      ],
    },

    /* ==================== DAY 3 ==================== */
    {
      id: 'sep1_d3_warmup', day: 'Day 3 · Thu Sept 3', availableFrom: '2026-09-03', order: 80,
      title: 'Warm-Up', subtitle: '3 questions · typed answers', scoring: 'none', timeLimitS: null,
      items: [
        { id: 'd3w1', type: 'numeric', skills: ['scale-area'], prompt: 'Two similar triangles have perimeters in the ratio $2:5$. What is the ratio of their areas? (Enter as a ratio such as 3:7.)', answer: '4:25', accept: ['4/25', '4 to 25'],
          explain: 'Perimeters are lengths, so the length factor is $2:5$; areas scale by its square, $4:25$.' },
        { id: 'd3w2', type: 'numeric', skills: ['stats-median-grouped'], prompt: 'A data set consists of the value 2 three times, the value 4 twice, and the value 7 four times. What is the median of the data set?', answer: '4',
          explain: 'Nine values in order: 2, 2, 2, 4, 4, 7, 7, 7, 7. The 5th value is 4.' },
        { id: 'd3w3', type: 'numeric', skills: ['sign-reversal', 'answer-asked'], prompt: 'If $5m - 5n = 40$, what is the value of $n - m$?', answer: '-8',
          explain: '$m - n = 8$, so $n - m = -8$. The question asks for the reversed difference.' },
      ],
    },
    {
      id: 'sep1_d3_reading', day: 'Day 3 · Thu Sept 3', availableFrom: '2026-09-03', order: 90,
      title: 'Reading Comprehension Mini-Section', subtitle: 'SSAT rules · 2 passages · 12 questions · 10 minutes · timed', scoring: 'ssat', timeLimitS: 600,
      intro: [{ type: 'directions', html: '<b>Directions:</b> The timer starts when you press Begin — five minutes per passage. Read each passage carefully and then answer the questions about it. Before the questions for a passage appear, complete the line <i>"The author\'s point is …"</i> beneath it. For every question about a detail, find the line of the passage that proves the answer before choosing.' }],
      passages: [
        { id: 'p_fireflies', html: '<p>For most of the twentieth century, reports that thousands of fireflies could flash in perfect unison were dismissed by many scientists as an illusion. Observers in Southeast Asia had described whole riverbanks of trees pulsing with light, but the claim seemed to require a level of coordination that insects were not thought to possess. It was not until the early 1990s that researchers documented the phenomenon in the United States, in the Great Smoky Mountains, where one species, <i>Photinus carolinus</i>, gathers by the thousands each June.</p><p><i>Photinus carolinus</i> is one of roughly two thousand firefly species worldwide, and it belongs to the genus <i>Photinus</i>, a group whose members are found throughout North America. What sets <i>P. carolinus</i> apart is not its light but its timing. Males produce a burst of five to eight flashes, then go dark for about eight seconds. During that pause, neighboring males adjust their own rhythm, and within minutes an entire hillside is flashing and pausing together.</p><p>The mechanism appears to be simple. Each male responds to the flashes he sees nearby by resetting his internal timer, in much the way that a person clapping in a crowd unconsciously falls into step with those around them. No leader is required; the pattern emerges from thousands of individual adjustments. Researchers believe the synchrony helps females, which flash from the ground, to distinguish the signal of their own species from the flashes of other fireflies active at the same time.</p><p>Since the 1990s the display has drawn so many visitors that the national park now admits viewers by lottery. Scientists remain cautious, however, about attributing the synchrony to any single cause; several competing explanations are still being tested.</p>' },
        { id: 'p_savage', html: '<p>Augusta Savage was born in 1892 in Green Cove Springs, Florida, where as a child she shaped small figures from the red clay near her home. Her father, a minister, disapproved of the practice and at times destroyed her work, but she continued. In 1921 she moved to New York City and enrolled at Cooper Union, completing its four-year sculpture program in three years.</p><p>Two years later, Savage applied to a summer art program in France and was accepted, then rejected when the committee learned that she was Black. Rather than accept the decision quietly, she wrote to newspapers and made the case public. The program\'s decision did not change, but the episode established her as someone willing to confront discrimination in the art world directly. By the end of the decade she had won a fellowship that allowed her to study in Paris, where she produced some of her best-known work, including a bust of a Harlem boy titled <i>Gamin</i>.</p><p>When she returned to New York, Savage turned much of her energy toward teaching. In 1932 she opened a studio in Harlem that offered free instruction, and several of her students, among them the painter Jacob Lawrence, went on to significant careers. Her largest commission came in 1939, when she was asked to create a sculpture for the New York World\'s Fair. The result, a sixteen-foot work inspired by the song "Lift Every Voice and Sing," depicted a group of singers arranged as the strings of a harp. Savage could not afford to have it cast in bronze, and the plaster original was destroyed when the fair closed.</p><p>Historians often note that Savage\'s own output was relatively small. Her influence, they argue, is better measured in the artists she trained than in the works she left behind.</p>' },
      ],
      items: [
        { id: 'd3r1', type: 'reading', passage: 'p_fireflies', skills: ['rd-main-idea'], prompt: 'Which of the following best expresses the main idea of the passage?',
          choices: [['A', 'Fireflies in Southeast Asia flash in unison along riverbanks.'], ['B', 'The synchronized flashing of one firefly species, once doubted, has been documented and partly explained.'], ['C', 'The Great Smoky Mountains park admits visitors to the firefly display by lottery.'], ['D', 'Scientists have identified the single cause of synchronized flashing in fireflies.']], answer: 'B',
          explain: '(A) and (C) are true details that cover one paragraph each; (D) contradicts the final paragraph, which says scientists are cautious about any single cause.' },
        { id: 'd3r2', type: 'reading', passage: 'p_fireflies', skills: ['rd-detail'], prompt: 'According to the passage, after a burst of flashes a male <i>P. carolinus</i> goes dark for approximately',
          choices: [['A', 'five seconds'], ['B', 'eight seconds'], ['C', 'eight minutes'], ['D', 'five to eight minutes']], answer: 'B',
          explain: 'Paragraph 2: "then go dark for about eight seconds."' },
        { id: 'd3r3', type: 'reading', passage: 'p_fireflies', skills: ['rd-relationship'], prompt: 'Which of the following statements is supported by the passage?',
          choices: [['A', '<i>Photinus</i> is one species within the genus <i>Photinus carolinus</i>.'], ['B', '<i>Photinus carolinus</i> is one species within the genus <i>Photinus</i>.'], ['C', 'All fireflies in the genus <i>Photinus</i> flash in synchrony.'], ['D', '<i>Photinus carolinus</i> is found throughout Southeast Asia.']], answer: 'B',
          explain: 'Paragraph 2 states the species belongs to the genus <i>Photinus</i>. (A) reverses the relationship; (C) generalizes to the whole genus; (D) places the species on the wrong continent.' },
        { id: 'd3r4', type: 'reading', passage: 'p_fireflies', skills: ['rd-tone'], prompt: 'The author\'s tone in discussing the research on firefly synchrony can best be described as',
          choices: [['A', 'skeptical'], ['B', 'enthusiastic'], ['C', 'matter-of-fact'], ['D', 'alarmed']], answer: 'C',
          explain: 'The passage reports findings without judgment or excitement; the closing note of caution is descriptive, not skeptical. Matter-of-fact is the default for science writing.' },
        { id: 'd3r5', type: 'reading', passage: 'p_fireflies', skills: ['rd-inference'], prompt: 'The comparison to a person clapping in a crowd (paragraph 3) is used to show that',
          choices: [['A', 'fireflies imitate human behavior'], ['B', 'the synchrony arises without any leader directing it'], ['C', 'visitors to the park applaud the display'], ['D', 'the fireflies\' timing is set by a single dominant male']], answer: 'B',
          explain: 'The sentence after the comparison: "No leader is required; the pattern emerges from thousands of individual adjustments." (D) is the opposite of the passage\'s claim.' },
        { id: 'd3r6', type: 'reading', passage: 'p_fireflies', skills: ['rd-century'], prompt: 'The passage indicates that synchronized flashing was first documented in the United States in the',
          choices: [['A', 'eighteenth century'], ['B', 'nineteenth century'], ['C', 'first half of the twentieth century'], ['D', 'last decade of the twentieth century']], answer: 'D',
          explain: '"The early 1990s" belongs to the last decade of the twentieth century (1901–2000). The 1900s are the twentieth century, not the nineteenth.' },
        { id: 'd3r7', type: 'reading', passage: 'p_savage', skills: ['rd-main-idea'], prompt: 'Which of the following best expresses the main idea of the passage?',
          choices: [['A', 'Augusta Savage\'s largest sculpture was destroyed after the 1939 World\'s Fair.'], ['B', 'Augusta Savage overcame early obstacles to become a sculptor whose greatest legacy was her teaching.'], ['C', 'Augusta Savage\'s father destroyed the clay figures she made as a child.'], ['D', 'Augusta Savage produced more sculptures than any other artist in Harlem.']], answer: 'B',
          explain: 'The passage moves from obstacles to teaching and ends by stating her influence is measured in the artists she trained. (A) and (C) are single details; (D) contradicts "relatively small."' },
        { id: 'd3r8', type: 'reading', passage: 'p_savage', skills: ['rd-detail'], prompt: 'According to the passage, Savage completed Cooper Union\'s sculpture program in',
          choices: [['A', 'two years'], ['B', 'three years'], ['C', 'four years'], ['D', 'six years']], answer: 'B',
          explain: 'Paragraph 1: "completing its four-year sculpture program in three years." (C) is the program\'s length, not her time.' },
        { id: 'd3r9', type: 'reading', passage: 'p_savage', skills: ['rd-inference'], prompt: 'The passage suggests that Savage\'s public response to the French program\'s rejection',
          choices: [['A', 'persuaded the committee to reverse its decision'], ['B', 'ended her hopes of studying in Europe'], ['C', 'showed her willingness to challenge discrimination openly'], ['D', 'was criticized by other artists']], answer: 'C',
          explain: 'Paragraph 2: "the episode established her as someone willing to confront discrimination … directly." (A) contradicts "The program\'s decision did not change"; (B) contradicts the Paris fellowship.' },
        { id: 'd3r10', type: 'reading', passage: 'p_savage', skills: ['rd-vocab'], prompt: 'As used in the last paragraph, the word "output" most nearly means',
          choices: [['A', 'volume of sound'], ['B', 'body of finished work'], ['C', 'energy'], ['D', 'income']], answer: 'B',
          explain: '"Output" is contrasted with "the artists she trained," so it means the works she produced.' },
        { id: 'd3r11', type: 'reading', passage: 'p_savage', skills: ['rd-purpose'], prompt: 'The main purpose of the third paragraph is to',
          choices: [['A', 'describe Savage\'s years in Paris'], ['B', 'explain why the World\'s Fair sculpture was destroyed'], ['C', 'show how Savage\'s focus shifted toward teaching and large public work'], ['D', 'list the students who studied with Savage']], answer: 'C',
          explain: 'The paragraph opens with "turned much of her energy toward teaching" and then covers the World\'s Fair commission. (B) and (D) are single details within it; (A) is paragraph 2.' },
        { id: 'd3r12', type: 'reading', passage: 'p_savage', skills: ['rd-sequence'], prompt: 'The passage indicates that Savage opened her Harlem studio',
          choices: [['A', 'before she moved to New York'], ['B', 'before she studied in Paris'], ['C', 'after she returned from Paris'], ['D', 'after the World\'s Fair closed']], answer: 'C',
          explain: 'Paragraph 3 opens "When she returned to New York" and then gives 1932 for the studio; Paris was "by the end of the decade" of the 1920s. Order: New York (1921) → Paris → studio (1932) → World\'s Fair (1939).' },
      ],
    },
    {
      id: 'sep1_d3_verbal', day: 'Day 3 · Thu Sept 3', availableFrom: '2026-09-03', order: 100,
      title: 'Verbal Set', subtitle: '10 sentence completions (ISEE rules) + 6 analogies (SSAT rules) · 12 minutes', scoring: 'mixed', timeLimitS: 720,
      intro: [{ type: 'directions', html: '<b>Directions — Sentence Completions:</b> Select the word or pair of words that best completes the sentence. Before looking at the choices, predict the meaning of the missing word from the sentence\'s signal words and decide whether it is positive or negative.<br><b>Directions — Analogies:</b> Write the bridge sentence first; the choices appear once it is written.' }],
      items: [
        { id: 'd3v1', type: 'completion', skills: ['vocab-completion', 'w:ruse'], prompt: 'Rather than confront the guard, the prisoners relied on a -------: one pretended to be ill while the others slipped past.', choices: [['A', 'ruse'], ['B', 'precedent'], ['C', 'tome'], ['D', 'parody']], answer: 'A', explain: '<b>ruse</b> — a trick; the colon introduces the trick itself.' },
        { id: 'd3v2', type: 'completion', skills: ['vocab-completion', 'w:judicious'], prompt: 'The committee praised the treasurer\'s ------- management of the budget; every expense had been weighed carefully against its benefit.', choices: [['A', 'vacuous'], ['B', 'judicious'], ['C', 'transient'], ['D', 'prolific']], answer: 'B', explain: '<b>judicious</b> — showing good judgment; the semicolon restates it ("weighed carefully").' },
        { id: 'd3v3', type: 'completion', skills: ['vocab-completion', 'w:enigma'], prompt: 'The cause of the ancient city\'s sudden abandonment remains an ------- that no excavation has resolved.', choices: [['A', 'ardor'], ['B', 'amelioration'], ['C', 'enigma'], ['D', 'delineation']], answer: 'C', explain: '<b>enigma</b> — a mystery; "no excavation has resolved" is the clue.' },
        { id: 'd3v4', type: 'completion', skills: ['vocab-completion', 'w:incorrigible'], prompt: 'Although the coach tried every approach, the ------- player kept ignoring instructions.', choices: [['A', 'demure'], ['B', 'solicitous'], ['C', 'incorrigible'], ['D', 'deft']], answer: 'C', explain: '<b>incorrigible</b> — not able to be corrected; "although … every approach" signals it.' },
        { id: 'd3v5', type: 'completion', skills: ['vocab-completion', 'w:solicitous'], prompt: 'The nurse was so ------- toward the frightened patient, checking on him every few minutes, that he soon relaxed.', choices: [['A', 'solicitous'], ['B', 'incorrigible'], ['C', 'vacuous'], ['D', 'transient']], answer: 'A', explain: '<b>solicitous</b> — attentive and concerned; "checking on him every few minutes" restates it. The word is unrelated to <i>soliciting</i>.' },
        { id: 'd3v6', type: 'completion', skills: ['vocab-completion', 'w:usurp'], prompt: 'The general\'s ------- of power from the elected council was condemned by neighboring nations.', choices: [['A', 'culmination'], ['B', 'usurpation'], ['C', 'amelioration'], ['D', 'penchant']], answer: 'B', explain: '<b>usurpation</b> — seizing power without right; "condemned" confirms the negative charge.' },
        { id: 'd3v7', type: 'completion', skills: ['vocab-completion', 'w:culminate'], prompt: 'Years of training ------- in a single performance that the critics called flawless.', choices: [['A', 'belittled'], ['B', 'squandered'], ['C', 'culminated'], ['D', 'rued']], answer: 'C', explain: '<b>culminated</b> — reached a high point; "years of training … in a single performance."' },
        { id: 'd3v8', type: 'completion', skills: ['vocab-completion', 'w:parody'], prompt: 'The comedian\'s ------- of the evening news copied the anchor\'s gestures so exactly that the audience roared.', choices: [['A', 'parody'], ['B', 'precedent'], ['C', 'crypt'], ['D', 'tome']], answer: 'A', explain: '<b>parody</b> — an imitation for comic effect; "copied the anchor\'s gestures … roared."' },
        { id: 'd3v9', type: 'completion', skills: ['vocab-completion', 'w:penchant'], prompt: 'Her ------- for collecting old maps eventually filled three rooms of the house.', choices: [['A', 'amelioration'], ['B', 'penchant'], ['C', 'rue'], ['D', 'delineation']], answer: 'B', explain: '<b>penchant</b> — a strong liking; "penchant for" is the standard construction.' },
        { id: 'd3v10', type: 'completion', skills: ['vocab-completion', 'w:engrossing', 'w:deft'], prompt: 'The lecture was so ------- that the students, expecting to be bored, were surprised to find the hour had passed; the professor\'s ------- storytelling had held them.', choices: [['A', 'vacuous . . demure'], ['B', 'engrossing . . deft'], ['C', 'transient . . prolific'], ['D', 'replete . . malleable']], answer: 'B', explain: '<b>engrossing . . deft</b> — the students were absorbed (positive, contradicting "expecting to be bored"), and the skillful storytelling explains why. (A) is negative in both blanks; (C) and (D) do not fit the sentence\'s logic.' },
        { id: 'd3a1', type: 'analogy', skills: ['analogy-bridge', 'w:deft', 'w:demure'], prompt: 'Deft is to clumsy as', choices: [['A', 'judicious is to careful'], ['B', 'prolific is to productive'], ['C', 'demure is to bold'], ['D', 'transient is to brief'], ['E', 'replete is to full']], answer: 'C', explain: 'Bridge: <i>deft</i> is the opposite of <i>clumsy</i>. Demure (shy, reserved) is the opposite of bold. The other pairs are synonyms.' },
        { id: 'd3a2', type: 'analogy', skills: ['analogy-bridge', 'w:pedagogue'], prompt: 'Pedagogue is to teach as', choices: [['A', 'surgeon is to operate'], ['B', 'student is to grade'], ['C', 'author is to read'], ['D', 'critic is to perform'], ['E', 'patient is to diagnose']], answer: 'A', explain: 'Bridge: a <i>pedagogue</i>\'s job is to <i>teach</i>. A surgeon\'s job is to operate. In the other pairs the action is done <i>to</i> or <i>by someone other than</i> the first word.' },
        { id: 'd3a3', type: 'analogy', skills: ['analogy-bridge', 'w:enigma', 'w:parody'], prompt: 'Enigma is to puzzling as', choices: [['A', 'tome is to brief'], ['B', 'crypt is to lively'], ['C', 'parody is to mocking'], ['D', 'precedent is to novel'], ['E', 'ruse is to honest']], answer: 'C', explain: 'Bridge: an <i>enigma</i> is by definition <i>puzzling</i>. A parody is by definition mocking. The other pairs give a quality the first word lacks.' },
        { id: 'd3a4', type: 'analogy', skills: ['analogy-bridge', 'w:squander'], prompt: 'Squander is to money as', choices: [['A', 'hoard is to shortage'], ['B', 'waste is to time'], ['C', 'earn is to salary'], ['D', 'belittle is to praise'], ['E', 'rue is to celebration']], answer: 'B', explain: 'Bridge: to <i>squander</i> is to waste <i>money</i>. To waste is to waste time — the same action applied to a comparable resource. (D) and (E) are antonym pairs, a different relationship.' },
        { id: 'd3a5', type: 'analogy', skills: ['analogy-bridge', 'w:belittle', 'w:usurp'], prompt: 'Belittle is to praise as', choices: [['A', 'ameliorate is to improve'], ['B', 'usurp is to surrender'], ['C', 'culminate is to end'], ['D', 'delineate is to outline'], ['E', 'engross is to absorb']], answer: 'B', explain: 'Bridge: <i>belittle</i> is the opposite of <i>praise</i>. Usurp (seize) is the opposite of surrender. The other pairs are synonyms.' },
        { id: 'd3a6', type: 'analogy', skills: ['analogy-bridge', 'w:transient', 'w:malleable'], prompt: 'Transient is to permanence as', choices: [['A', 'malleable is to rigidity'], ['B', 'vacuous is to emptiness'], ['C', 'solicitous is to concern'], ['D', 'prolific is to abundance'], ['E', 'incorrigible is to stubbornness']], answer: 'A', explain: 'Bridge: something <i>transient</i> lacks <i>permanence</i>. Something malleable lacks rigidity. In (B) through (E), the noun is the quality the adjective <i>has</i>.' },
      ],
    },
    {
      id: 'sep1_d3_secondpass', day: 'Day 3 · Thu Sept 3', availableFrom: '2026-09-03', order: 110,
      title: 'Second Pass — Test Innovators', subtitle: 'Wednesday\'s ✗ questions, cold again', scoring: 'none', timeLimitS: null, dynamicFrom: 'sep1_d2_review',
      intro: [{ type: 'directions', html: '<b>Directions:</b> This list is built from Wednesday\'s Review Set — every question marked ✗ there. Rework each cold on the platform and mark it. A question missed both days needs a new error-log line beginning <i>"Different this time:"</i> that names what changed.' }],
      items: [],
    },

    /* ==================== DAY 4 ==================== */
    {
      id: 'sep1_d4_card', day: 'Day 4 · Fri Sept 4', availableFrom: '2026-09-04', order: 120,
      title: 'Test-Day Card — SSAT Upper Level, Saturday', subtitle: 'Rest day · read once, aloud', scoring: 'none', timeLimitS: null, type: 'card',
      html: '<p><b>Say before each section:</b> <i>"This is the SSAT. Right +1, wrong −¼, blank 0. I guess only after eliminating two."</i></p><h4>Pacing</h4><ul><li><b>Quantitative (25 questions per section):</b> about one minute each. Minutes left on the section timer beyond 25 are the review reserve — for flagged questions, not new ones.</li><li><b>Reading (40 questions, 40 minutes):</b> five minutes per passage, all passages reached. Forty-five seconds is the cap on any single question; past that, mark the best of what is left or leave it blank and move on.</li><li><b>Verbal (60 questions, 30 minutes):</b> thirty seconds each. Synonyms first pass fast; analogies get the bridge sentence before the choices.</li></ul><h4>Rituals that hold under pressure</h4><ul><li><b>Reading:</b> "The author\'s point is ___" before the questions; finger on the proving line for every detail question; matter-of-fact is the default tone for science writing.</li><li><b>Quantitative:</b> re-read the last sentence before marking; the intermediate number is usually a choice. Function notation: solve the argument first. Scaling: lengths ×k, areas ×k², volumes ×k³. Percent changes multiply.</li><li><b>Verbal:</b> charge first (+/−), part of speech second, then eliminate. Two eliminations make the guess worth taking; fewer means blank.</li><li><b>Unknown word:</b> roots and prefixes, then charge, then eliminate — the strategy only needs to remove two choices.</li></ul><h4>After the test</h4><ul><li>Enter answers on the platform. Turn <b>Review Mode off</b> before saving each missed-question PDF so the solution is included.</li><li>The test is finished when the error log is written — every miss, one line each, before any analysis is read.</li></ul>',
      items: [],
    },
  ],

  figures: {
    hist_books: '<svg viewBox="0 0 340 230" width="340" height="230" role="img" aria-label="Histogram of books read"><line class="ax" x1="50" y1="180" x2="336" y2="180"/><line class="ax" x1="50" y1="180" x2="50" y2="20"/><line class="tk" x1="46" y1="180" x2="50" y2="180"/><text x="42" y="184" font-size="11" text-anchor="end">0</text><line class="tk" x1="46" y1="160" x2="50" y2="160"/><text x="42" y="164" font-size="11" text-anchor="end">1</text><line class="tk" x1="46" y1="140" x2="50" y2="140"/><text x="42" y="144" font-size="11" text-anchor="end">2</text><line class="tk" x1="46" y1="120" x2="50" y2="120"/><text x="42" y="124" font-size="11" text-anchor="end">3</text><line class="tk" x1="46" y1="100" x2="50" y2="100"/><text x="42" y="104" font-size="11" text-anchor="end">4</text><line class="tk" x1="46" y1="80" x2="50" y2="80"/><text x="42" y="84" font-size="11" text-anchor="end">5</text><line class="tk" x1="46" y1="60" x2="50" y2="60"/><text x="42" y="64" font-size="11" text-anchor="end">6</text><line class="tk" x1="46" y1="40" x2="50" y2="40"/><text x="42" y="44" font-size="11" text-anchor="end">7</text><line class="tk" x1="46" y1="20" x2="50" y2="20"/><text x="42" y="24" font-size="11" text-anchor="end">8</text><rect class="bar" x="60" y="120" width="36" height="60"/><text x="78" y="196" font-size="12" text-anchor="middle">0</text><rect class="bar" x="106" y="80" width="36" height="100"/><text x="124" y="196" font-size="12" text-anchor="middle">1</text><rect class="bar" x="152" y="40" width="36" height="140"/><text x="170" y="196" font-size="12" text-anchor="middle">2</text><rect class="bar" x="198" y="60" width="36" height="120"/><text x="216" y="196" font-size="12" text-anchor="middle">3</text><rect class="bar" x="244" y="140" width="36" height="40"/><text x="262" y="196" font-size="12" text-anchor="middle">4</text><rect class="bar" x="290" y="160" width="36" height="20"/><text x="308" y="196" font-size="12" text-anchor="middle">5</text><text x="198" y="216" font-size="12" text-anchor="middle">Number of books read</text><text transform="translate(14,100) rotate(-90)" font-size="12" text-anchor="middle">Number of students</text></svg>',
    pie_lunch: '<svg viewBox="0 0 330 215" width="330" height="215" role="img" aria-label="Pie chart of favorite lunch"><path class="bar" d="M110,105 L110.0,20.0 A85,85 0 0,1 178.8,155.0 Z"/><text x="158.5" y="84.3" font-size="11" text-anchor="middle">35%</text><text x="215" y="40" font-size="13">Pizza — 35%</text><path class="bar" d="M110,105 L178.8,155.0 A85,85 0 0,1 60.0,173.8 Z"/><text x="118.5" y="162.7" font-size="11" text-anchor="middle">25%</text><text x="215" y="68" font-size="13">Tacos — 25%</text><path class="bar" d="M110,105 L60.0,173.8 A85,85 0 0,1 26.5,120.9 Z"/><text x="64.1" y="138.1" font-size="11" text-anchor="middle">12%</text><text x="215" y="96" font-size="13">Salad — 12%</text><path class="bar" d="M110,105 L26.5,120.9 A85,85 0 0,1 29.2,78.7 Z"/><text x="55.7" y="105.6" font-size="11" text-anchor="middle">8%</text><text x="215" y="124" font-size="13">Soup — 8%</text><path class="bar" d="M110,105 L29.2,78.7 A85,85 0 0,1 110.0,20.0 Z"/><text x="78.0" y="65.0" font-size="11" text-anchor="middle">20%</text><text x="215" y="152" font-size="13">Other — 20%</text><text x="110" y="208" font-size="12" text-anchor="middle" font-style="italic">Favorite lunch, 200 students</text></svg>',
  },
};
